const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const num=v=>Math.max(0,Number(v)||0);
const storeKey='pristine_estimator_docs_v1', brandKey='pristine_estimator_brand_v1';
const addonDefaults=[['Floor removal / demolition',0,1.5],['Floor prep / patching',0,1.25],['Baseboard installation',0,2.5],['Furniture moving',0,75]];
let docMode='ESTIMATE';
function addAddon(name='',qty=0,rate=0){const row=document.createElement('div');row.className='addon-row';row.innerHTML=`<input aria-label="Add-on name" value="${name}"><input aria-label="Quantity" type="number" min="0" step="0.01" value="${qty}"><input aria-label="Rate" type="number" min="0" step="0.01" value="${rate}"><button type="button" aria-label="Remove add-on">×</button>`;row.querySelectorAll('input').forEach(i=>i.addEventListener('input',calc));row.querySelector('button').addEventListener('click',()=>{row.remove();calc()});$('#addons').append(row)}
addonDefaults.forEach(a=>addAddon(...a));
function state(){const sqft=num($('#sqft').value),waste=Math.min(40,num($('#waste').value)),required=sqft*(1+waste/100),matRate=num($('#materialRate').value),labRate=num($('#laborRate').value);let addons=[];$$('.addon-row').forEach(r=>{const ins=r.querySelectorAll('input');addons.push({name:ins[0].value||'Custom item',qty:num(ins[1].value),rate:num(ins[2].value)})});const addonsTotal=addons.reduce((s,a)=>s+a.qty*a.rate,0);const material=required*matRate,labor=sqft*labRate,total=material+labor+addonsTotal;return{customer:{name:$('#customerName').value,phone:$('#customerPhone').value,email:$('#customerEmail').value,zip:$('#customerZip').value,address:$('#projectAddress').value},sqft,waste,required,materialType:$('#materialType').value,pattern:$('#pattern').value,materialRate:matRate,laborRate:labRate,material,labor,addons,addonsTotal,total,notes:$('#notes').value,brand:getBrand()}}
function calc(){const s=state();$('#requiredSqft').textContent=`${Math.round(s.required).toLocaleString()} sq ft`;$('#materialTotal').textContent=money(s.material);$('#laborTotal').textContent=money(s.labor);$('#addonsTotal').textContent=money(s.addonsTotal);$('#grandTotal').textContent=money(s.total)}
['sqft','waste','materialRate','laborRate'].forEach(id=>$('#'+id).addEventListener('input',calc));$('#materialType').addEventListener('change',calc);$('#pattern').addEventListener('change',()=>{const p=$('#pattern').value;const hints={Diagonal:'Diagonal layouts usually require more cuts and waste.',Herringbone:'Herringbone is labor-intensive and typically needs additional waste.',Chevron:'Chevron requires precision cuts and usually increases labor.', 'Large Format Tile':'Large-format tile may require flatter substrate and specialized handling.'};$('#patternHint').textContent=hints[p]||'Straight installation is typically the most efficient layout.';});$('#addAddonBtn').addEventListener('click',()=>addAddon('Custom add-on',1,0));
function getDocs(){try{return JSON.parse(localStorage.getItem(storeKey)||'[]')}catch{return[]}} function setDocs(v){localStorage.setItem(storeKey,JSON.stringify(v));renderDocs()}
function getBrand(){try{return JSON.parse(localStorage.getItem(brandKey)||'{}')}catch{return{}}}
function saveBrand(){localStorage.setItem(brandKey,JSON.stringify({name:$('#brandName').value,phone:$('#brandPhone').value,email:$('#brandEmail').value}));}
function ensureCustomer(s){return s.customer.name||s.customer.phone||s.customer.email}
function saveDoc(type){const s=state();if(!ensureCustomer(s)){alert('Add at least a customer name, phone or email before saving.');return null}const docs=getDocs();const prefix=type==='INVOICE'?'INV':'EST';const id=`${prefix}-${String(Date.now()).slice(-6)}`;docs.unshift({id,type,date:new Date().toISOString(),...s});setDocs(docs);return id}
$('#saveEstimateBtn').addEventListener('click',()=>saveDoc('ESTIMATE'));$('#invoiceBtn').addEventListener('click',()=>{const id=saveDoc('INVOICE');if(id){docMode='INVOICE';printDoc(state(),id)}});$('#printEstimateBtn').addEventListener('click',()=>{docMode='ESTIMATE';const id=saveDoc('ESTIMATE')||`EST-${String(Date.now()).slice(-6)}`;printDoc(state(),id)});
function printDoc(s,id){const b=s.brand||{};const win=window.open('','_blank');const rows=s.addons.filter(a=>a.qty*a.rate>0).map(a=>`<tr><td>${a.name}</td><td>${a.qty}</td><td>${money(a.rate)}</td><td>${money(a.qty*a.rate)}</td></tr>`).join('');win.document.write(`<!doctype html><html><head><title>${docMode} ${id}</title><style>body{font-family:Arial,sans-serif;color:#16191d;margin:36px}header{display:flex;justify-content:space-between;border-bottom:3px solid #171a20;padding-bottom:18px;margin-bottom:24px}.brand{font-size:24px;font-weight:900}.muted{color:#6d737d}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:22px 0}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}.total{font-size:24px;font-weight:900;text-align:right;margin-top:20px}.cta{margin-top:34px;padding:18px;background:#171a20;color:#fff}.small{font-size:12px}</style></head><body><header><div><div class="brand">${b.name||'PRISTINE FLOORING'}</div><div class="muted">${b.phone||'(561) 806-3322'} ${b.email?`• ${b.email}`:''}</div></div><div><strong>${docMode}</strong><br>${id}<br><span class="muted">${new Date().toLocaleDateString()}</span></div></header><div class="grid"><div><strong>Customer</strong><br>${s.customer.name||'-'}<br>${s.customer.phone||''}<br>${s.customer.email||''}</div><div><strong>Project</strong><br>${s.customer.address||'-'}<br>${s.sqft.toLocaleString()} measured sq ft<br>${Math.round(s.required).toLocaleString()} required sq ft</div></div><table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody><tr><td>${s.materialType} material</td><td>${Math.round(s.required)} sq ft</td><td>${money(s.materialRate)}</td><td>${money(s.material)}</td></tr><tr><td>${s.pattern} installation</td><td>${s.sqft} sq ft</td><td>${money(s.laborRate)}</td><td>${money(s.labor)}</td></tr>${rows}</tbody></table><div class="total">Total: ${money(s.total)}</div>${s.notes?`<p><strong>Notes:</strong><br>${s.notes}</p>`:''}<div class="cta"><strong>Need flooring materials?</strong><br>Contact Pristine Flooring • (561) 806-3322<br><span class="small">Powered by Aureon Ecosystem</span></div><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close()}
function renderDocs(){const docs=getDocs();const customers=new Set(docs.map(d=>d.customer?.email||d.customer?.phone||d.customer?.name).filter(Boolean));$('#statCustomers').textContent=customers.size;$('#statEstimates').textContent=docs.filter(d=>d.type==='ESTIMATE').length;$('#statInvoices').textContent=docs.filter(d=>d.type==='INVOICE').length;$('#statValue').textContent=money(docs.filter(d=>d.type==='ESTIMATE').reduce((s,d)=>s+(d.total||0),0));const box=$('#savedList');if(!docs.length){box.innerHTML='<p class="empty">No saved documents yet.</p>';return}box.innerHTML='';docs.forEach((d,i)=>{const row=document.createElement('div');row.className='saved-item';row.innerHTML=`<div><div class="doc-type">${d.type}</div><strong>${d.id}</strong></div><span>${d.customer?.name||'Unnamed customer'}</span><strong>${money(d.total)}</strong><button class="secondary-btn" type="button">Open / PDF</button>`;row.querySelector('button').addEventListener('click',()=>{docMode=d.type;printDoc(d,d.id)});box.append(row)})}
$('#clearBtn').addEventListener('click',()=>{if(confirm('Clear all locally saved estimates and invoices?'))setDocs([])});
$('#brandBtn').addEventListener('click',()=>{const b=getBrand();$('#brandName').value=b.name||'';$('#brandPhone').value=b.phone||'';$('#brandEmail').value=b.email||'';$('#brandDialog').showModal()});$('#saveBrandBtn').addEventListener('click',saveBrand);
calc();renderDocs();
