const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const num=v=>Math.max(0,Number(v)||0);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storeKey='pristine_estimator_docs_v2',brandKey='pristine_estimator_brand_v2';
const addonDefaults=[['Floor removal / demolition',0,1.5],['Floor prep / patching',0,1.25],['Baseboard installation',0,2.5],['Furniture moving',0,75]];
let docMode='ESTIMATE';
function addAddon(name='',qty=0,rate=0){const row=document.createElement('div');row.className='addon-row';row.innerHTML=`<input aria-label="Add-on name" value="${esc(name)}"><input aria-label="Quantity" type="number" min="0" step="0.01" value="${qty}"><input aria-label="Rate" type="number" min="0" step="0.01" value="${rate}"><button type="button" aria-label="Remove add-on">×</button>`;row.querySelectorAll('input').forEach(i=>i.addEventListener('input',calc));row.querySelector('button').addEventListener('click',()=>{row.remove();calc()});$('#addons').append(row)}
addonDefaults.forEach(a=>addAddon(...a));
function getBrand(){try{return JSON.parse(localStorage.getItem(brandKey)||'{}')}catch{return{}}}
function state(){const sqft=num($('#sqft').value),waste=Math.min(40,num($('#waste').value)),required=sqft*(1+waste/100),matRate=num($('#materialRate').value),labRate=num($('#laborRate').value);let addons=[];$$('.addon-row').forEach(r=>{const ins=r.querySelectorAll('input');addons.push({name:ins[0].value||'Custom item',qty:num(ins[1].value),rate:num(ins[2].value)})});const addonsTotal=addons.reduce((s,a)=>s+a.qty*a.rate,0),material=required*matRate,labor=sqft*labRate,total=material+labor+addonsTotal;return{customer:{name:$('#customerName').value,phone:$('#customerPhone').value,email:$('#customerEmail').value,zip:$('#customerZip').value,address:$('#projectAddress').value},sqft,waste,required,materialType:$('#materialType').value,pattern:$('#pattern').value,materialRate:matRate,laborRate:labRate,material,labor,addons,addonsTotal,total,notes:$('#notes').value,brand:getBrand()}}
function calc(){const s=state();$('#requiredSqft').textContent=`${Math.round(s.required).toLocaleString()} sq ft`;$('#summaryMeasured').textContent=`${Math.round(s.sqft).toLocaleString()} sq ft`;$('#summaryRequired').textContent=`${Math.round(s.required).toLocaleString()} sq ft`;$('#summaryPattern').textContent=s.pattern;$('#materialTotal').textContent=money(s.material);$('#laborTotal').textContent=money(s.labor);$('#addonsTotal').textContent=money(s.addonsTotal);$('#grandTotal').textContent=money(s.total);$('#mobileTotal').textContent=money(s.total)}
['sqft','waste','materialRate','laborRate'].forEach(id=>$('#'+id).addEventListener('input',calc));$('#materialType').addEventListener('change',calc);$('#pattern').addEventListener('change',()=>{const p=$('#pattern').value;const hints={Diagonal:'Diagonal layouts usually require more cuts and waste.',Herringbone:'Herringbone is labor-intensive and typically needs additional waste.',Chevron:'Chevron requires precision cuts and usually increases labor.','Large Format Tile':'Large-format tile may require flatter substrate and specialized handling.','1/3 Offset':'A 1/3 offset can help reduce lippage with many plank-style tiles.','1/2 Offset / Brick':'Brick layouts may need layout adjustments depending on tile warpage.'};$('#patternHint').textContent=hints[p]||'Straight installation is typically the most efficient layout.';calc()});
$('#addAddonBtn').addEventListener('click',()=>addAddon('Custom add-on',1,0));$$('[data-addon]').forEach(b=>b.addEventListener('click',()=>addAddon(b.dataset.addon,1,Number(b.dataset.rate)||0)));
function getDocs(){try{return JSON.parse(localStorage.getItem(storeKey)||'[]')}catch{return[]}}
function setDocs(v){localStorage.setItem(storeKey,JSON.stringify(v));renderDocs()}
function saveBrand(){localStorage.setItem(brandKey,JSON.stringify({name:$('#brandName').value,phone:$('#brandPhone').value,email:$('#brandEmail').value}))}
function ensureCustomer(s){return s.customer.name||s.customer.phone||s.customer.email}
function saveDoc(type){const s=state();if(!ensureCustomer(s)){alert('Add at least a customer name, phone or email before saving.');return null}const docs=getDocs(),prefix=type==='INVOICE'?'INV':'EST',id=`${prefix}-${String(Date.now()).slice(-6)}`;docs.unshift({id,type,date:new Date().toISOString(),...s});setDocs(docs);return{id,data:s}}
$('#saveEstimateBtn').addEventListener('click',()=>saveDoc('ESTIMATE'));
$('#invoiceBtn').addEventListener('click',()=>{const x=saveDoc('INVOICE');if(x){docMode='INVOICE';printDoc(x.data,x.id)}});
$('#printEstimateBtn').addEventListener('click',()=>{docMode='ESTIMATE';const x=saveDoc('ESTIMATE');if(x)printDoc(x.data,x.id)});
function printDoc(s,id){const b=s.brand||{},win=window.open('','_blank');if(!win){alert('Please allow pop-ups to generate the PDF.');return}const rows=s.addons.filter(a=>a.qty*a.rate>0).map(a=>`<tr><td>${esc(a.name)}</td><td>${a.qty}</td><td>${money(a.rate)}</td><td>${money(a.qty*a.rate)}</td></tr>`).join('');const mainBrand=b.name||'PRISTINE FLOORING';const contact=[b.phone,b.email].filter(Boolean).map(esc).join(' · ');const partner=b.name?'<div class="partner">Material partner: <strong>PRISTINE FLOORING</strong> · (561) 806-3322</div>':'';win.document.write(`<!doctype html><html><head><title>${docMode} ${esc(id)}</title><style>body{font-family:Arial,sans-serif;color:#16191d;margin:36px;line-height:1.4}header{display:flex;justify-content:space-between;gap:24px;border-bottom:4px solid #171a20;padding-bottom:18px;margin-bottom:24px}.brand{font-size:26px;font-weight:900}.muted{color:#6d737d}.partner{margin-top:6px;font-size:12px;color:#6d737d}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:22px 0}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}th{font-size:11px;text-transform:uppercase;letter-spacing:.05em}.total{font-size:26px;font-weight:900;text-align:right;margin-top:20px}.cta{margin-top:34px;padding:18px;background:#171a20;color:#fff}.small{font-size:11px;color:#c8ccd1}</style></head><body><header><div><div class="brand">${esc(mainBrand)}</div>${contact?'<div class="muted">'+contact+'</div>':''}${partner}</div><div><strong>${docMode}</strong><br>${esc(id)}<br><span class="muted">${new Date().toLocaleDateString()}</span></div></header><div class="grid"><div><strong>Customer</strong><br>${esc(s.customer.name||'-')}<br>${esc(s.customer.phone||'')}<br>${esc(s.customer.email||'')}</div><div><strong>Project</strong><br>${esc(s.customer.address||'-')}<br>${Math.round(s.sqft).toLocaleString()} measured sq ft<br>${Math.round(s.required).toLocaleString()} required sq ft</div></div><table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody><tr><td>${esc(s.materialType)} material</td><td>${Math.round(s.required)} sq ft</td><td>${money(s.materialRate)}</td><td>${money(s.material)}</td></tr><tr><td>${esc(s.pattern)} installation</td><td>${Math.round(s.sqft)} sq ft</td><td>${money(s.laborRate)}</td><td>${money(s.labor)}</td></tr>${rows}</tbody></table><div class="total">Total: ${money(s.total)}</div>${s.notes?'<p><strong>Notes:</strong><br>'+esc(s.notes)+'</p>':''}<div class="cta"><strong>Need flooring materials?</strong><br>Contact Pristine Flooring · (561) 806-3322<br><span class="small">Powered by Aureon Ecosystem</span></div><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close()}
function renderDocs(){const docs=getDocs(),customers=new Set(docs.map(d=>d.customer?.email||d.customer?.phone||d.customer?.name).filter(Boolean));$('#statCustomers').textContent=customers.size;$('#statEstimates').textContent=docs.filter(d=>d.type==='ESTIMATE').length;$('#statInvoices').textContent=docs.filter(d=>d.type==='INVOICE').length;$('#statValue').textContent=money(docs.filter(d=>d.type==='ESTIMATE').reduce((s,d)=>s+(d.total||0),0));const box=$('#savedList');if(!docs.length){box.innerHTML='<p class="empty">No saved documents yet.</p>';return}box.innerHTML='';docs.forEach(d=>{const row=document.createElement('div');row.className='saved-item';row.innerHTML=`<div><div class="doc-type">${esc(d.type)}</div><strong>${esc(d.id)}</strong></div><span>${esc(d.customer?.name||'Unnamed customer')}</span><strong>${money(d.total)}</strong><button class="secondary-btn" type="button">Open / PDF</button>`;row.querySelector('button').addEventListener('click',()=>{docMode=d.type;printDoc(d,d.id)});box.append(row)})}
$('#clearBtn').addEventListener('click',()=>{if(confirm('Clear all locally saved estimates and invoices?'))setDocs([])});
$('#brandBtn').addEventListener('click',()=>{const b=getBrand();$('#brandName').value=b.name||'';$('#brandPhone').value=b.phone||'';$('#brandEmail').value=b.email||'';$('#brandDialog').showModal()});$('#saveBrandBtn').addEventListener('click',saveBrand);
$('#mobileReviewBtn').addEventListener('click',()=>$('#estimateSummary').scrollIntoView({behavior:'smooth',block:'start'}));
calc();renderDocs();